title: Hasan'ın Blogu
description: Modern ve etkileyici kişisel blog
baseurl: "/hasanmuruz"
url: "https://hasangokaymuruz.github.io"

# Tema ayarları
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Eklentiler
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Varsayılanlar
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
