title: Hasan'ın Blogu
description: Kişisel blog ve yazılarım
baseurl: "/hasanmuruz"  # ÖNEMLİ: Repository adınız
url: "https://hasangokaymuruz.github.io"

# Tema
remote_theme: pages-themes/hacker@v0.2.0

# Eklentiler
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
